language: go

go: 1.9.1

install:
- go get github.com/golang/dep/cmd/dep
- go get github.com/mitchellh/gox
- dep ensure
- go vet
- gox -os "freebsd darwin linux windows" -arch "386 amd64"
script:
- go test
